# -*- mode: python ; coding: utf-8 -*-
import sys
sys.setrecursionlimit(10000)

# --- PIL C 扩展二进制（_imaging.pyd 等） ---
import glob, os
import PIL
_pil_dir = PIL.__path__[0]
_pil_pyds = [(f, 'PIL') for f in glob.glob(os.path.join(_pil_dir, '*.pyd'))]

a = Analysis(
    [r'E:\download\Tools\Docflowing/desktop_app.py'],
    pathex=[r'E:\download\Tools\Docflowing'],
    binaries=list(_pil_pyds),
    datas=[
    (r'E:\download\Tools\Docflowing\ui', 'ui'),
    (r'E:\download\Tools\Docflowing\kb\skills\system', 'kb/skills/system'),
    (r'E:\download\Tools\Docflowing\tools', 'tools'),
    (r'E:\download\Tools\Docflowing\kb\fts_ext', 'kb/fts_ext'),
    (r'C:\Program Files\Python313\Lib\site-packages\pythonnet\runtime', 'pythonnet/runtime'),
    ],
    hiddenimports=[
        'kb',
        'kb.auto_extract',
        'kb.config',
        'kb.context_compressor',
        'kb.context_fence',
        'kb.database',
        'kb.file_lock',
        'kb.file_safety',
        'kb.insights',
        'kb.interrupt',
        'kb.llm',
        'kb.memory',
        'kb.models',
        'kb.routes',
        'kb.routes_session',
        'kb.routes_memory',
        'kb.routes_insights',
        'kb.routes_skills',
        'kb.search',
        'kb.session_db',
        'kb.sync_converters',
        'kb.sync_state',
        'kb.sync_subprocess',
        'kb.sync_worker',
        'kb.user_tools',
        'kb.agent_tools',
        'kb.skills',
        'kb.skills.manager',
        'kb.skills.curator',
        'kb.skills.usage',
        'fb',
        'fb.models',
        'fb.routes',
        'fb.routes_base',
        'fb.routes_files',
        'fb.routes_files_edit',
        'fb.routes_files_ops',
        'fb.routes_locks',
        'fb.routes_p2p',
        'fb.routes_search',
        'fb.routes_sync',
        'fb.routes_tools',
        'fb.routes_trash',
        'fb.database',
        'fb.decorators',
        'p2p',
        'p2p.node',
        'p2p.discovery',
        'p2p.auth',
        'p2p.api',
        'p2p.models',
        'p2p.proxy',
        'server',
        'server.auth',
        'server.middleware',
        'server.runner',
        'server.settings',
        'server.workspace',
        'server.tool_runner',
        'webview',
        'webview.platforms.edgechromium',
        'webview.platforms.winforms',
        'webview.platforms.win32',
        'pythonnet',
        'clr_loader',
        'clr_loader.netfx',
        'clr_loader.types',
        'logging_config',
        'doc_process',
        'mystyle',
        'to_compare',
        'to_docx',
        'to_redhead',
        'to_index',
        'to_pageNum',
        'to_pdf',
        'float_picture',
        'load_config',
        'tool_defs',
        'WordKeepAlive',
        'flask',
        'flask_cors',
        'zeroconf',
        'yaml',
        'requests',
        'pdfplumber',
        'bs4',
        'beautifulsoup4',
        'markitdown',
        'openpyxl',
        'docx',
        'pptx',
        'pystray',
        'PIL',
        'PIL._imaging',
        'PIL._tkinter_finder',
        'PIL.Image',
        'PIL.ImageTk',
        'packaging',
        'tkinter',
        '_tkinter',
        'win32com',
        'pythoncom',
        'win32api',
        'win32con',
        'win32gui',
        'pywintypes',
        'docx2pdf',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'unittest',
        'pdb',
        'test',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'matplotlib',
        'scipy',
        'notebook',
        'jupyter',
        'IPython',
        'numpy.testing',
        'pandas',
        'cefpython3',
        'cryptography',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name='Docflowing',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=['*.pyd'],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=True,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=r'E:\download\Tools\Docflowing\ui\favicon.ico',
    contents_directory='.',
    onefile=False,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=['*.pyd'],
    name='Docflowing',
)
