# -*- mode: python ; coding: utf-8 -*-
import sys
sys.setrecursionlimit(10000)

# --- PIL C 扩展二进制（_imaging.pyd 等） ---
import glob, os
import PIL
_pil_dir = PIL.__path__[0]
# 只收集 PIL 核心 pyd，跳过 _avif(28MB)/_webp/_imagingft/_imagingcms 等格式插件
_pil_skip = {'_avif', '_webp', '_imagingft', '_imagingcms', '_imagingtk', '_imagingmorph'}
_pil_pyds = [(f, 'PIL') for f in glob.glob(os.path.join(_pil_dir, '*.pyd'))
             if os.path.basename(f).split('.')[0] not in _pil_skip]

# SPECPATH：PyInstaller 注入的 spec 文件所在目录。用它派生所有项目内路径，
# build.spec 即可跨盘符/跨机器直接使用（相对路径本身会按运行 cwd 解析，不可靠）。
a = Analysis(
    [os.path.join(SPECPATH, 'desktop_app.py')],
    pathex=[SPECPATH],
    binaries=list(_pil_pyds),
    datas=[
    (os.path.join(SPECPATH, 'ui/favicon.ico'), 'ui'),
    (os.path.join(SPECPATH, 'ui/index.html'), 'ui'),
    (os.path.join(SPECPATH, 'ui/js/fb.css'), 'ui/js'),
    (os.path.join(SPECPATH, 'ui/js/fb.js'), 'ui/js'),
    (os.path.join(SPECPATH, 'ui/js/kb.css'), 'ui/js'),
    (os.path.join(SPECPATH, 'ui/js/kb.js'), 'ui/js'),
    (os.path.join(SPECPATH, 'ui/js/main.js'), 'ui/js'),
    (os.path.join(SPECPATH, 'ui/js/tab-manager.js'), 'ui/js'),
    (os.path.join(SPECPATH, 'ui/js/tools.js'), 'ui/js'),
    (os.path.join(SPECPATH, 'ui/js/utils.js'), 'ui/js'),
    (os.path.join(SPECPATH, 'kb/skills/system'), 'kb/skills/system'),
    (os.path.join(SPECPATH, 'tools'), 'tools'),
    (os.path.join(SPECPATH, 'kb/fts_ext'), 'kb/fts_ext'),
    (r'F:\Program Files\python312\Lib\site-packages\pythonnet\runtime', 'pythonnet/runtime'),
    ],
    hiddenimports=[
        'kb',
        'kb.auto_extract',
        'kb.config',
        'kb.context_compressor',
        'kb.context_fence',
        'kb.database',
        'kb.file_lock',
        'kb.file_safety',
        'kb.insights',
        'kb.interrupt',
        'kb.llm',
        'kb.memory',
        'kb.models',
        'kb.routes',
        'kb.routes_session',
        'kb.routes_memory',
        'kb.routes_insights',
        'kb.routes_skills',
        'kb.search',
        'kb.session_db',
        'kb.sync_converters',
        'kb.sync_state',
        'kb.sync_subprocess',
        'kb.sync_worker',
        'kb.user_tools',
        'kb.agent_tools',
        'kb.skills',
        'kb.skills.manager',
        'kb.skills.curator',
        'kb.skills.usage',
        'fb',
        'fb.models',
        'fb.routes',
        'fb.routes_base',
        'fb.routes_files',
        'fb.routes_files_edit',
        'fb.routes_files_ops',
        'fb.routes_locks',
        'fb.routes_p2p',
        'fb.routes_search',
        'fb.routes_sync',
        'fb.routes_tools',
        'fb.routes_trash',
        'fb.database',
        'fb.decorators',
        'p2p',
        'p2p.node',
        'p2p.discovery',
        'p2p.auth',
        'p2p.api',
        'p2p.models',
        'p2p.proxy',
        'server',
        'server.auth',
        'server.middleware',
        'server.runner',
        'server.settings',
        'server.workspace',
        'server.tool_runner',
        'webview',
        'webview.platforms.edgechromium',
        'webview.platforms.winforms',
        'webview.platforms.win32',
        'pythonnet',
        'clr_loader',
        'clr_loader.netfx',
        'clr_loader.types',
        'logging_config',
        'doc_process',
        'mystyle',
        'to_compare',
        'to_docx',
        'to_redhead',
        'to_index',
        'to_pageNum',
        'to_pdf',
        'float_picture',
        'load_config',
        'tool_defs',
        'WordKeepAlive',
        'flask',
        'flask_cors',
        'zeroconf',
        'yaml',
        'requests',
        'bs4',
        'beautifulsoup4',
        'markitdown',
        'openpyxl',
        'docx',
        'pptx',
        'pystray',
        'PIL',
        'PIL._imaging',
        'PIL._tkinter_finder',
        'PIL.Image',
        'PIL.ImageTk',
        'packaging',
        'tkinter',
        '_tkinter',
        'win32com',
        'pythoncom',
        'win32api',
        'win32con',
        'win32gui',
        'pywintypes',
        'docx2pdf',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'unittest',
        'pdb',
        'test',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'matplotlib',
        'scipy',
        'notebook',
        'jupyter',
        'IPython',
        'numpy.testing',
        'pandas',
        'cefpython3',
        'cryptography',
        'magika',
        'onnxruntime',
        'onnx',
        'win32ui',
        'PIL._avif',
        'PIL._webp',
        'PIL._imagingft',
        'PIL._imagingcms',
        'numpy',
        'pdfminer',
        'pdfplumber',
        'pypdfium2',
        'pypdfium2_raw',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name='Docflowing',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=['*.pyd', '*.dll'],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=True,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=os.path.join(SPECPATH, 'ui', 'favicon.ico'),
    contents_directory='.',
    onefile=False,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=['*.pyd', '*.dll'],
    name='Docflowing',
)
