# -*- mode: python ; coding: utf-8 -*-
import sys
sys.setrecursionlimit(10000)

a = Analysis(
    [r'E:\download\learn\Docflowing/desktop_app.py'],
    pathex=[r'E:\download\learn\Docflowing'],
    binaries=[],
    datas=[
    (r'E:\download\learn\Docflowing\ui', 'ui'),
    (r'E:\download\learn\Docflowing\kb\skills\system', 'kb/skills/system'),
    (r'E:\download\learn\Docflowing\tools', 'tools'),
    (r'E:\download\learn\Docflowing\kb\fts_ext', 'kb/fts_ext'),
    ],
    hiddenimports=[
        # ========== KB 模块 ==========
        'kb',
        'kb.auto_extract',
        'kb.config',
        'kb.context_compressor',
        'kb.context_fence',
        'kb.database',
        'kb.file_lock',
        'kb.file_safety',
        'kb.insights',
        'kb.interrupt',
        'kb.llm',
        'kb.memory',
        'kb.models',
        'kb.routes',
        'kb.routes_session',
        'kb.routes_memory',
        'kb.routes_insights',
        'kb.routes_skills',
        'kb.search',
        'kb.session_db',
        'kb.sync_converters',
        'kb.sync_state',
        'kb.sync_subprocess',
        'kb.sync_worker',
        'kb.user_tools',
        'kb.agent_tools',
        'kb.skills',
        'kb.skills.manager',
        'kb.skills.curator',
        'kb.skills.usage',
        # ========== FB 模块 ==========
        'fb',
        'fb.models',
        'fb.routes',
        'fb.routes_base',
        'fb.routes_files',
        'fb.routes_files_edit',
        'fb.routes_files_ops',
        'fb.routes_locks',
        'fb.routes_p2p',
        'fb.routes_search',
        'fb.routes_sync',
        'fb.routes_tools',
        'fb.routes_trash',
        'fb.database',
        'fb.decorators',
        # ========== P2P 模块 ==========
        'p2p',
        'p2p.node',
        'p2p.discovery',
        'p2p.auth',
        'p2p.api',
        'p2p.models',
        'p2p.proxy',
        # ========== Server 模块 ==========
        'server',
        'server.auth',
        'server.middleware',
        'server.runner',
        'server.settings',
        'server.workspace',
        # ========== pywebview（edgechromium 后端） ==========
        'webview',
        'webview.platforms.edgechromium',
        'webview.platforms.winforms',
        'webview.platforms.windows',
        # ========== Tools（Python 模块形式引入） ==========
        'logging_config',
        'doc_process',
        'mystyle',
        'to_compare',
        'to_docx',
        'to_redhead',
        'to_index',
        'to_pageNum',
        'to_pdf',
        'float_picture',
        'load_config',
        'tool_defs',
        'WordKeepAlive',
        # ========== 第三方隐式依赖 ==========
        'flask',
        'flask_cors',
        'zeroconf',
        'yaml',
        'cryptography',
        'requests',
        'pdfplumber',
        'bs4',
        'beautifulsoup4',
        'markitdown',
        'openpyxl',
        'docx',
        'pptx',
        'pystray',
        'PIL',
        'PIL._tkinter_finder',
        'PIL.Image',
        'PIL.ImageTk',
        'appdirs',
        'packaging',
        # ========== Windows 可选依赖（COM + Word） ==========
        'win32com',
        'pythoncom',
        'win32api',
        'win32con',
        'win32gui',
        'pywintypes',
        'docx2pdf',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # 注意：不排除 tkinter —— desktop_app.py 的文件选择/保存对话框依赖它
        'unittest',
        'pdb',
        'test',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'matplotlib',
        'scipy',
        'notebook',
        'jupyter',
        'IPython',
        'numpy.testing',
        'pandas',
        'cefpython3',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name='文澜',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    contents_directory='.',
)

# onedir 模式（保持目录结构便于调试 + 资源文件按原生路径读写）
# 若要切换为单文件模式，将 EXE 改为 COLLECT + 独立 EXE(onefile=True)。
